language: php
sudo: false

os:
  - linux

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer clear-cache
  - composer update

script:
  - ./vendor/bin/parallel-lint --exclude vendor src
  - ./vendor/bin/phpunit --testdox
  - ./vendor/bin/psalm
  - ./vendor/bin/phpcs --standard=PSR2 -n src
