language: php
sudo: false

os:
  - linux

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - composer update

script:
  - ./vendor/bin/parallel-lint --exclude vendor src
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - php -v | grep -q 'PHP 7.' || ./vendor/bin/phpunit -v
  - php -v | grep -q 'PHP 7.' || ./vendor/bin/psalm
